services:
  - type: web
    name: carlinigomme-relay-py
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
